language: cpp
compiler:
  - gcc
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install --user -r requirements.txt
  - pip install --user cpp-coveralls
# command to run tests
script: 
  - make -C vm COVERAGE=1
  - nosetests -v
after_success:
  - coveralls --gcov-options '\-lp' -i $PWD/vm/ubpf_vm.c
